spring-xsuaa-test: rename private/publicKey files to avoid clashes
IllegalArgumentException: failed to construct sequence from byte[]: DEF length 1213 object truncated by 2